account/urls.py
from django_registration.backends.activation.views import RegistrationView
from .forms import MyCustomUserForm
from django.urls import path
from .views import edit, sign_up, log_in, log_out, edit_profile, index, details, register, CustomUserLoginView, UsersListView, UserProfileView, user_details
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views # or import built in classes as follows
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)

"""
path('accounts/', include('django.contrib.auth.urls')),
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
"""
app_name = 'account'
urlpatterns = [
    path('', index, name='index'), # <a href="/accounts/"> Home</a>  accounts/ need permission
    #path('<int:pk>', prof_edit, name='profile_edit'),  # <str:username>
    path('profile/', details, name='profile'), # The user redirected to this view to see his profile
    path('profile/<str:username>/', user_details, name='user_profile'), # when the user click on someones profile name redirect to this view
    path('profile/<str:username>/edit/', edit_profile, name='edit_profile'),
    #path('signup/', RegistrationView.as_view(form_class=MyCustomUserForm), name='signup',),
    path('signup/', sign_up, name='signup'),
    path('login/', CustomUserLoginView.as_view(), name='login'), # CustomUserLoginView.as_view()
    path('logout/', log_out, name='logout'),
    #path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='accounts/profile'), name= 'login'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='/'), name= 'logout'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='user/password_reset.html',
        email_template_name='user/password_reset_email.html',
        subject_template_name='user/password_reset_subject.txt',
        success_url='/user/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html',
        success_url='/user/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    # the following password reset templates is the default ones, so you have to create them if you don't want to use default
    # ... some built-in auth-views & other customizable ones
    path('password_change/', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('accounts/password_change_done')),
        name='password_change'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),), # use the builtin name='password_change'
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]
"""
urlpatterns = [ 
    path('about/', login_required(TemplateView.as_view(template_name="secret.html"))), 
    path('vote/', permission_required('polls.can_vote')(VoteView.as_view())), 
]  
"""

job/urls.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from job.models import Job
from . import views
from django.urls import  path, include
from rest_framework import routers, renderers
from rest_framework.routers import DefaultRouter
from .serializers import JobSerializer
from rest_framework.urlpatterns import format_suffix_patterns
#from .api import JobDetial, JobList, JobViewSet, UserViewSet, jobDetailViewSet, jobViewSet
from . import api
app_name='job'
# Create a router and register our viewsets with it.
# Routers provide an easy way of automatically determining the URL conf.
router = DefaultRouter() # router = router.DefaultRouter() 
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)
router.register(r'jobs', api.JobViewSet)
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('api/', include(router.urls)),
    path('index/', views.index, name='index'),
    path('', views.job_list, name='job_list'),
    path('add/', views.job_post, name='add'),
    path('<str:slug>/', views.job_details, name='details'),             
]
# or 
#urlpatterns = format_suffix_patterns(urlpatterns)
#urlpatterns += [path('api/', include(router.urls)),]

project/urls.py
import debug_toolbar
from django import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
#import blog.api, job.api
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
#Add URL maps to redirect the base URL to our application
from rest_framework.routers import DefaultRouter
from django.views.generic import RedirectView 
# Add Django site authentication urls (for login, logout, password management)
# Use static() to add url mapping to serve static files during development (only)
API_TITLE = 'Site API'
API_DESCRIPTION = 'A Web API for creating and viewing highlighted code snippets.'
schema_view = get_schema_view(title=API_TITLE)
urlpatterns = [
    path('admin', admin.site.urls),
    #re_path(r'^schema/$', schema_view), # old deprecated
    #re_path(r'^docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)), # old deprecated
    path('openapi', get_schema_view(title="My Project", description="API for all things …"), name='openapi-schema'), # the newest one
    # to get the built-in authinticatuion views login/logout/change_password/etc...
    #path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('contacts/', include('contact.urls', namespace='contacts')),
    path('jobs/', include('job.urls', namespace='jobs')), 
    #re_path(r'^blog/', include('blog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    #re_path(r"^messages/", include("messages.urls", namespace="messages")), it was pinax.message but i took it outside the pinax abn made it free
    path('messages/', include('postman.urls', namespace='postman')), # just alternated by pinax.messages
    path("chat/", include("chat.urls", namespace='chat')),
    re_path(r'chat2/', include('django_private_chat2.urls', namespace='django_private_chat2')),
    #re_path(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')), # has no relation with others blog urls only for login to api
    path('__debug__/', include(debug_toolbar.urls)), # after install django-debug-toolbar
] + staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ...
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
django_private_chat2 doesn't provide any endpoint to fetch users (required to start new chat,
for example) It's up to you to do so.
The example app does it in urls.py so feel free to copy the handler from there if you wish.
'''

account/forms.py
from django import forms
from django.db.models import fields
from django.shortcuts import get_object_or_404
from .models import Profile
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from gettext import translation
from .models import User #you can use get_user_model
# -*- coding: utf-8 -*-
from django import forms
#from django.utils.translation import gettext_lazy as _
from account.models import Profile
from django.contrib.auth.models import Group
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django_registration.forms import RegistrationForm
from account.models import User
# the simplest one if you didn't creat a custom user model
# in user app you can put User Creation Form here
# for user creation w/o custom model you need only username and passwod

class UserForm(UserCreationForm): # SignUp or register Form
    # if you added any field here will override the built-in field, so we just want to
    # use some of the built in fields(username, email, password)  and not changes it as follows
    class Meta:
        model = User
        fields = ['username', 'email',]
class DateInput(forms.DateInput):
    input_type = 'date'
# Edit Profile form
class ProForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        widgets = {
            'date_of_birth': DateInput(),
        }
        exclude = ('user',)
# or establish new form fields here, if a new form ==> class take (forms.Form)

class LoginForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField(label = "Password", widget = forms.PasswordInput)

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password")

class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    photo = forms.ImageField(required=False)
    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username
    def clean_username(self):
        """
        This function throws an exception if the username has already been taken by another user
        """
        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username
        
class MyCustomUserForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = User
        fields = {'username', 'email', 'password1', 'password2'}

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = {'username', 'email', 'password1', 'password2'}
    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.name = self.cleaned_data['name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

# Next form if you extend Both AbstractBaseUser / if AbstractUser that already has the same auth.User model, there is no need
# for this form at all just use the 1st simlest one above all as it's the same as the above one but used for auth user
class CustomUserCreationForm(UserCreationForm): # as we have a odel but has only username as emails
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput) # You can remove those two fields as they are already been existed
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    class Meta(UserCreationForm.Meta): # UserCreationForm has already all default fields, so you just need to add the additional fields to it
        model = User
        #fields = UserCreationForm.Meta.fields + ('user_type',)  # birth date's been removed and added to profile model
        fields = ('username', 'email', ) # if you have any other special field add it here
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2
    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM.
        username = self.cleaned_data["username"]
        try:
            #User.objects.get(username=username)
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class CustomUserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()
    group = Group()
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password',)

# to allow only some active users to log in
"""
from django.contrib.auth.forms import AuthenticationForm
class PickyAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                _("This account is inactive."),
                code='inactive',
            )
        if user.username.startswith('b'):
            raise forms.ValidationError(
                _("Sorry, accounts starting with 'b' aren't welcome here."),
                code='no_b_users',
            )
"""
from django import forms
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.contrib.admin.widgets import FilteredSelectMultiple    
User = get_user_model()
# Create ModelForm based on the Group model.
class GroupAdminForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = []
    # Add the users field.
    users = forms.ModelMultipleChoiceField(
         queryset=User.objects.all(), 
         required=False,
         # Use the pretty 'filter_horizontal widget'.
         widget=FilteredSelectMultiple('users', False)
    )
    def __init__(self, *args, **kwargs):
        # Do the normal form initialisation.
        super(GroupAdminForm, self).__init__(*args, **kwargs)
        # If it is an existing group (saved objects have a pk).
        if self.instance.pk:
            # Populate the users field with the current Group users.
            self.fields['users'].initial = self.instance.user_set.all()

    def save_m2m(self):
        # Add the users to the Group.
        self.instance.user_set.set(self.cleaned_data['users'])

    def save(self, *args, **kwargs):
        # Default save
        instance = super(GroupAdminForm, self).save()
        # Save many-to-many data
        self.save_m2m()
        return instance

account/templates/index.html
{% extends 'layout.html' %} {% load static %} {% load django_bootstrap5 %} {% block body %}
<section id="about" class="about-area bg-dark section-padding">
    <div class="contain">
        <div class="header">
            <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <!-- Adding the message in the template -->
                        {% for message in messages %}
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                        </div>
                        {% endfor %}
                        <br>
                        <br>
                        <h2>{% block head_title %}Number of Users: {{ users_num }}{% endblock %}</h2>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
        <div class="col-lg-12">
            <div class="user_filter white-bg">
                <div class="form_inner bg-dark">
                    <h3>Filter</h3>
                    <form method='GET'>
                        {{ form.non_field_errors }} {% csrf_token %} {% for field in filter.form %}
                        <div class="apply">
                            {% if field.errors %}
                            <ol>
                                {% for error in field.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            </ol>
                            {% endif %} {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                        {% endfor %} {% bootstrap_form filter.form %}
                        <input value='find' class="boxed-btn3 w-10 mt-2" type="submit">
                    </form>
                    <div class="reset_btn">
                        {% if has_filter %}<button class="boxed-btn3 w-100" type="submit"><a href="{%  url 'accounts:index' %}">Reset</a> </button> {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="mainbody">
            <div class="container">
                <div class="row d-flex align-items-center">
                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <div class="row">
                            <div class="user_lists m-0">
                                <div class="row">
                                    {% for user in users %}
                                    <ul>
                                        <li>
                                            <a href="{% url 'accounts:user_profile' user.username %}">
                                                <h3>{{user.username}}</h3>
                                            </a>
                                            <h6>Email: {{user.email}}</h6>
                                            <h6>First Name: {{user.first_name}}</h6>
                                            <h6>Last Name: {{user.last_name}}</h6>
                                            <p> <i class="fa fa-clock-o"></i> User Type : {{user.user_type}}</p>
                                            <!-- <p>Birth Date : {{ user.date_of_birth|date:"d M o" }}</p> -->
                                        </li>
                                    </ul>
                                    {% endfor %}
                                </div>
                            </div>
                            {% if users.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if users.has_previous %}
                                            <li>
                                                <a href="?page={{ users.previous_page_number }}"> <i class="ti-angle-left"></i> </a>
                                            </li>
                                            {% endif %} {% for i in users.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endfor %} {% if users.has_next %}
                                            <li>
                                                <a href="?page={{ users.next_page_number }}"> <i class="ti-angle-right"></i> </a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}