job/urls.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from job.models import Job
from . import views
from django.urls import  path, include
from rest_framework import routers, renderers
from rest_framework.routers import DefaultRouter
from .serializers import JobSerializer
from rest_framework.urlpatterns import format_suffix_patterns
#from .api import JobDetial, JobList, JobViewSet, UserViewSet, jobDetailViewSet, jobViewSet
from . import api
app_name='job'
# Create a router and register our viewsets with it.
# Routers provide an easy way of automatically determining the URL conf.
router = DefaultRouter() # router = router.DefaultRouter() 
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)
router.register(r'jobs', api.JobViewSet)
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('api/', include(router.urls)),
    path('index/', views.index, name='index'),
    path('', views.job_list, name='job_list'),
    path('add/', views.job_post, name='add'),
    path('<str:slug>/', views.job_details, name='details'),             
]
# or 
#urlpatterns = format_suffix_patterns(urlpatterns)
#urlpatterns += [path('api/', include(router.urls)),]

project/urls.py
import debug_toolbar
from django import urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
#import blog.api, job.api
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
#Add URL maps to redirect the base URL to our application
from rest_framework.routers import DefaultRouter
from django.views.generic import RedirectView 
# Add Django site authentication urls (for login, logout, password management)
# Use static() to add url mapping to serve static files during development (only)
API_TITLE = 'Site API'
API_DESCRIPTION = 'A Web API for creating and viewing highlighted code snippets.'
schema_view = get_schema_view(title=API_TITLE)
urlpatterns = [
    path('admin', admin.site.urls),
    #re_path(r'^schema/$', schema_view), # old deprecated
    #re_path(r'^docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)), # old deprecated
    path('openapi', get_schema_view(title="My Project", description="API for all things …"), name='openapi-schema'), # the newest one
    # to get the built-in authinticatuion views login/logout/change_password/etc...
    #path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('contacts/', include('contact.urls', namespace='contacts')),
    path('jobs/', include('job.urls', namespace='jobs')), 
    #re_path(r'^blog/', include('blog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('home.urls', namespace='home')),
    #re_path(r"^messages/", include("messages.urls", namespace="messages")), it was pinax.message but i took it outside the pinax abn made it free
    path('messages/', include('postman.urls', namespace='postman')), # just alternated by pinax.messages
    path("chat/", include("chat.urls", namespace='chat')),
    re_path(r'chat2/', include('django_private_chat2.urls', namespace='django_private_chat2')),
    #re_path(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')), # has no relation with others blog urls only for login to api
    path('__debug__/', include(debug_toolbar.urls)), # after install django-debug-toolbar
] + staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# ...
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
django_private_chat2 doesn't provide any endpoint to fetch users (required to start new chat,
for example) It's up to you to do so.
The example app does it in urls.py so feel free to copy the handler from there if you wish.
'''

job/models.py
#from django.contrib.auth.models import User
from account.models import User
from django.db import models
from django.template.defaultfilters import slugify # from django.utils.text import slugify
from django.urls import reverse
#import os

def upload_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/apply/<title>/<filename>
    # return os.path.join("uploads", filename)
    return 'apply/{0}/{1}'.format(instance.name, filename)
def directory_path(instance, filename):
    imgName, extension = filename.split('.')
    imgName = instance.title
    return 'jobs/%s.%s' %(imgName, extension)
JOB_TYPE = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
)
class Job(models.Model):
    employer = models.OneToOneField(User, related_name='recruiter', on_delete=models.CASCADE,)
    #owner = models.ForeignKey('auth.User', related_name='job_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, default='')
    job_type = models.CharField(max_length=15, choices=JOB_TYPE, default='Full Time',)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now_add=True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True)  # relations
    job_icon = models.ImageField(upload_to=directory_path, null=False, blank=True)
    slug = models.SlugField(null=True, blank=True)
    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Job, self).save(*args, **kwargs)
    def get_absolute_url(self):
        # or ==>  kwargs={ "slug": str(self.slug] })
        return reverse('details', kwargs={'slug': self.slug})
    class Meta:
        ordering = ['title']
    def __str__(self) -> str:
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=25)
    def __str__(self) -> str:
        return self.name
    class Meta:
        verbose_name_plural = 'Categories'

class Applicant(models.Model):
    name = models.CharField(max_length=100)
    applicant = models.OneToOneField(User, related_name='applicant', on_delete=models.CASCADE)
    job = models.ForeignKey(Job, related_name='apply', on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    website = models.URLField(blank=True)
    cv = models.FileField(upload_to=upload_path, null=True, blank=True)
    cover_letter = models.TextField(max_length=500, blank=True)
    date_of_application = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.name

job/forms.py
from django import forms
from django.db.models import fields
from .models import Applicant, Job
class Apply(forms.ModelForm):
    class Meta:
        model = Applicant
        fields = ['name', 'email', 'cover_letter',
                  'website', 'cv']  # or ==> fields = '__all__'
class PostJob(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ('employer','slug')

job/views.py
import datetime
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from .forms import Apply, PostJob
from django.shortcuts import render
from .models import Job
from .filters import JobFilter
from django.core.paginator import Paginator
def index(request):
    jobs = Job.objects.all()
    return render(request, 'job/index.html', {'jobs': jobs})

def job_list(request):
    jobs_list = Job.objects.all()
    filter = JobFilter(request.GET, queryset=jobs_list)
    jobs_list = filter.qs
    paginator = Paginator(jobs_list, 5)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'jobs': page_obj, 'filter': filter, 'jobs_list':jobs_list}  # jobs is the key name to use in template
    return render(request, 'job/jobs.html', context)

def job_details(request, slug):
    job_details = Job.objects.get(slug=slug)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Apply(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            apply = form.save(commit=False)
            apply.job = job_details  # apply is the related_name in applicant model to job model
            apply.applicant = request.user 
            apply.save()
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/contacts/thanks')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = Apply()
    context = {'job': job_details, 'form': form}
    return render(request, 'job/job_details.html', context)
@login_required
def job_post(request):
    if request.method == 'POST':
        form = PostJob(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.employer = request.user
            post.save()
            return redirect(reverse('jobs:job_list'))
            #return HttpResponseRedirect('/success/url/')
    else:
        form = PostJob()
    return render(request, 'job/add_job.html', {'form': form})

job/templates/job/add_job.html
{% extends 'layout.html' %} {% load django_bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_dark_bg">
    <div class="header">
        <div class="row">
            <div class="col-sm-12">
                <div class="section-title">
                    <!-- Adding the message in the template -->
                    <br>
                    <br>
                    <h2>{% block head_title %} {% endblock %}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Add New Job</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_details_area bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <div class="job_details_header">
                    <div class="single_jobs bg-dark d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#">
                                    <h4></h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> </p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{ job.job_type }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="apply_job_form bg-dark">
                    <h4>Post A Job</h4>
                    <form method='POST' class="form" enctype='multipart/form-data'>
                        {{ form.non_field_errors }} {% csrf_token %} {% for field in form %}
                        <div class="apply">
                            {% if field.errors %}
                            <ol>
                                {% for error in field.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            </ol>
                            {% endif %} {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                        {% endfor %} {% bootstrap_form form %}
                        <button class="boxed-btn3 w-100" type="submit">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

job/templates/job/job_details.html
{% extends 'layout.html' %} {% load django_bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_dark_bg">
    <div class="header">
        <div class="row">
            <div class="col-sm-12">
                <div class="section-title">
                    <!-- Adding the message in the template -->
                    <br>
                    <br>
                    <h2>{% block head_title %} Details {% endblock %}</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_details_area bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs bg-dark d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="{% url 'jobs:details' job.slug %}">
                                    <h4>{{job.title}}</h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{ job.job_type }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap bg-dark">
                    <div class="single_wrap">
                        <h4>Job description</h4>
                        <p>{{ job.description }}</p>
                    </div>
                    <div class="single_wrap">
                        <h4>Responsibility</h4>
                        <ul>
                            <li>
                            </li>
                        </ul>
                    </div>
                    <div class="single_wrap">
                        <h4>Qualifications</h4>
                        <ul>
                            <li>
                            </li>
                        </ul>
                    </div>
                    <div class="single_wrap">
                    </div>
                </div>
                <div class="apply_job_form bg-dark">
                    <h4>Apply for the job</h4>
                    <form method='POST' class="form" enctype='multipart/form-data'>
                        {{ form.non_field_errors }} {% csrf_token %} {% for field in form %}
                        <div class="apply">
                            {% if field.errors %}
                            <ol>
                                {% for error in field.errors %}
                                <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            </ol>
                            {% endif %} {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </div>
                        {% endfor %} {% bootstrap_form form %}
                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary bg-dark">
                    <h3>Job Summery</h3>
                    <br><br>
                    <div class="">
                        <ul>
                            <li>Published on: <span>{{ job.published_at|date:"d M o" }}</span></li>
                            <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                            <li>Salary: <span>{{job.salary}}k/y</span></li>
                            <li>Location: <span>California, USA</span></li>
                            <li>Job Nature: <span> {{job.job_type}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li>
                            <a href="#"> <i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-envelope"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                                var uluru = {
                                    lat: -25.363,
                                    lng: 131.044
                                };
                                var grayStyles = [{
                                    featureType: "all",
                                    stylers: [{
                                        saturation: -90
                                    }, {
                                        lightness: 50
                                    }]
                                }, {
                                    elementType: 'labels.text.fill',
                                    stylers: [{
                                        color: '#ccdee9'
                                    }]
                                }];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    center: {
                                        lat: -31.197,
                                        lng: 150.744
                                    },
                                    zoom: 9,
                                    styles: grayStyles,
                                    scrollwheel: false
                                });
                            }
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

job/templates/job/jobs.html
{% extends 'layout.html' %} {% load static %} {% load django_bootstrap5 %} {% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_dark_bg">
    <div class="header">
        <div class="row">
            <div class="col-sm-12">
                <div class="section-title">
                    <!-- Adding the message in the template -->
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="section-title">
                    <h2>{% block head_title %} Jobs {% endblock %}</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bradcam_area bradcam_dark_bg">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{ jobs_list.count }}+ Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter bg-dark">
                    <div class="form_inner bg-dark">
                        <h3>Filter</h3>
                        <form method='GET'>
                            {{ form.non_field_errors }} {% csrf_token %} {% for field in filter.form %}
                            <div class="apply">
                                {% if field.errors %}
                                <ol>
                                    {% for error in field.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %} {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                            {% endfor %} {% bootstrap_form filter.form %}
                            <input value='find' class="boxed-btn3 w-10 mt-2" type="submit">
                        </form>
                    </div>
                    <div class="reset_btn">
                        <button class="boxed-btn3 w-100" type="submit">Reset</button>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist dark_bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>
                            <div class="col-md-6">
                                <div class="serch_cat d-flex justify-content-end">
                                    <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for job in jobs %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs dark_bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'jobs:details' job.slug %}">
                                            <h4 style="color: rgb(208, 208, 221) ;">{{job.title}}</h4>
                                        </a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                        <a class="boxed-btn3" href="{% url 'jobs:details' job.slug %}">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <p>{{ job.published_at|date:"d M o" }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% if jobs.has_other_pages %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pagination_wrap">
                                <ul>
                                    {% if jobs.has_previous %}
                                    <li>
                                        <a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i> </a>
                                    </li>
                                    {% endif %} {% for i in jobs.paginator.page_range %}
                                    <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                    {% endfor %} {% if jobs.has_next %}
                                    <li>
                                        <a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->
{% endblock body %}